// Login
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILED = 'LOGIN_FAILED';

//login with core
export const LOGIN_WITH_CORE_REQUEST = 'LOGIN_WITH_CORE_REQUEST';
export const LOGIN_WITH_CORE_SUCCESS = 'LOGIN_WITH_CORE_SUCCESS';
export const LOGIN_WITH_CORE_FAILED = 'LOGIN_WITH_CORE_FAILED';

// customer dk onlines 


export const START_LIST_CUSTOMER_ONLINE = 'START_LIST_CUSTOMER_ONLINE';
export const SUCCESS_LIST_CUSTOMER_ONLINE = 'SUCCESS_LIST_CUSTOMER_ONLINE';
export const SUCCESS_PAGINATION_CUSTOMER_ONLINE = 'SUCCESS_PAGINATION_CUSTOMER_ONLINE';
export const ERROR_LIST_CUSTOMER_ONLINE = 'ERROR_LIST_CUSTOMER_ONLINE';

export const CUSTOMER_DETAIL_START = 'CUSTOMER_DETAIL_START';
export const CUSTOMER_DETAIL_SUCCESS = 'CUSTOMER_DETAIL_SUCCESS';
export const CUSTOMER_DETAIL_ERROR = 'CUSTOMER_DETAIL_ERROR';

export const START_CUSTOMER_APPROVE = 'START_CUSTOMER_APPROVE'
export const SUCCESS_CUSTOMER_APPROVE = 'SUCCESS_CUSTOMER_APPROVE'
export const ERROR_CUSTOMER_APPROVE = 'ERROR_CUSTOMER_APPROVE'
export const MG_LIST = 'MG_LIST'

export const START_LIST_BANKS = 'START_LIST_BANKS'
export const SUCCESS_LIST_BANKS = 'SUCCESS_LIST_BANKS'
export const ERROR_LIST_BANKS = 'ERROR_LIST_BANKS'

export const START_BRANCHES_BANKS = 'START_BRANCHES_BANKS'
export const SUCESS_BRANCHES_BANKS = 'SUCESS_BRANCHES_BANKS'
export const ERROR_BRANCHES_BANKS = 'ERROR_BRANCHES_BANKS'


export const START_DOWNLOAD_CONTRACT = 'START_DOWNLOAD_CONTRACT'
export const SCUESS_DOWNLOAD_CONTRACT = 'SCUESS_DOWNLOAD_CONTRACT'
export const ERROR_DOWNLOAD_CONTRACT = 'ERROR_DOWNLOAD_CONTRACT'


export const LIST_PHONG_GD = 'LIST_PHONG_GD'

export const CHANGE_PASSWORD = 'CHANGE_PASSWORD';
export const CHANGE_PASSWORD_SUCCESS = 'CHANGE_PASSWORD_SUCCESS';
export const CHANGE_PASSWORD_ERROR = 'CHANGE_PASSWORD_ERROR'

export const SET_BRANCH_NAMES = 'SET_BRANCH_NAMES'

export const SET_LIST_BROKERS = 'SET_LIST_BROKERS'




export const INDEXS = {
    INDEX: {
        POST: {},
        GET: [],
        ID: {},
        FILL_MONEY: [],
        REFRESH_PRICE: [],
        MANAGEMENT: {},
        ASSET_INFO: []
    },
    ORDER: {
        POST: {}
    },
    PROPORTION: {
        PUT: {}
    },
    UPLOAD: {
        ICON: {}
    }
}

export const HISTORY = {
    HISTORY: {
        LIST: [],
        INDEX_TIME: []
    }
}
